inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160
  Exclude:
    - spec/integration/purl_spec.rb

Metrics/AbcSize:
  Max: 22
  Exclude:
    - app/controllers/iiif_v2_controller.rb
    - app/controllers/iiif_v3_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/models/purl_resource.rb
    - app/models/iiif_presentation_manifest.rb
    - app/models/iiif3_presentation_manifest.rb

Metrics/MethodLength:
  Max: 23

Metrics/ModuleLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - app/models/purl_resource.rb
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
