inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
   Max: 160


Style/Documentation:
  Enabled: false