services:
  rustfs_server:
    image: rustfs/rustfs
    environment:
      RUSTFS_ACCESS_KEY: rustfs-user
      RUSTFS_SECRET_KEY: rustfs-password
    ports: ["9000:9000/tcp"]
    volumes:
      - rustfs_data:/data
volumes:
  rustfs_data:
