purl_resource:
  versioned:
    public_xml: "<%= File.join(Rails.root, "spec", "fixtures", "document_cache") %>/%{druid_tree}/%{druid}/versions/public.%{version_id}.xml"
    cocina: "<%= File.join(Rails.root, "spec", "fixtures", "document_cache") %>/%{druid_tree}/%{druid}/versions/cocina.%{version_id}.json"
    meta: "<%= File.join(Rails.root, "spec", "fixtures", "document_cache") %>/%{druid_tree}/%{druid}/versions/meta.json"

stacks:
  version_manifest_path: "<%= File.join(Rails.root, "spec", "fixtures", "document_cache") %>/%{druid_tree}/%{druid}/versions/versions.json"

content_search:
  url: "http://example.com/content_search/%{druid}/search"

resource_cache:
  enabled: false
